(ns diplomat.thingy
  "GENERATED by jolt-diplomat-backend from the real Diplomat HIR.
  Do not hand-edit — see findings/milestone-5-findings.md."
  (:require [jolt.ffi :as ffi]
            [diplomat.runtime :as dr]
            [diplomat.doubled :as doubled]
            [diplomat.mode :as mode]
  ))

(dr/defopaque Thingy "Thingy_destroy")

(ffi/defcfn ^:private c-apply-callback "jolt_Thingy_apply_callback" [:pointer :pointer :pointer :pointer] :uint8)
(defn apply-callback [self f]
  (let [f-state (atom nil)
      f-run-cb (ffi/foreign-callable
                    (fn [_data a0] (f a0))
                    [:pointer :uint8] :uint8 :collect-safe)
      f-destructor (ffi/foreign-callable
                        (fn [_data]
                          (let [{:keys [run-cb destructor]} @f-state]
                            (ffi/free-callable run-cb)
                            (ffi/free-callable destructor)))
                        [:pointer] :void :collect-safe)]
  (reset! f-state {:run-cb f-run-cb :destructor f-destructor})
    (c-apply-callback (:ptr self) ffi/null f-run-cb f-destructor)
  )
)

(ffi/defcfn ^:private c-try-create "jolt_Thingy_try_create" [:string :size_t :pointer] :void)
(ffi/defcfn ^:private c-sizeof-try-create-result "jolt_sizeof_Thingy_try_create_result" [] :int)
(defn try-create [s]
  (let [sz (c-sizeof-try-create-result) out (ffi/alloc sz)]
    (try
      (c-try-create s (count s) out)
      (dr/unwrap-result!
       (if (= 1 (ffi/read out :uint8 8))
         {:ok? true :value (->Thingy (ffi/read out :pointer 0) false)}
         {:ok? false :error (ffi/read out :int 0)})
       "Thingy/try-create")
      (finally (ffi/free out))))
)

(ffi/defcfn ^:private c-value "Thingy_value" [:pointer] :uint8)
(defn value [self] (c-value (:ptr self)))

(ffi/defcfn ^:private c-describe "jolt_Thingy_describe" [:pointer :int :double :pointer] :void)
(defn describe [self opts]
  (let [buf (ffi/alloc 256) w (ffi/alloc dr/writeable-struct-size)]
    (try
      (dr/simple-write! buf 256 w)
      (c-describe (:ptr self) (if (:verbose opts) 1 0) (:scale opts) w)
      (let [n (ffi/read w :size_t dr/O-len)] (ffi/read-bytes buf n))
      (finally (ffi/free buf) (ffi/free w))))
)

(ffi/defcfn ^:private c-sum-with "jolt_Thingy_sum_with" [:pointer :pointer :size_t] :uint)
(defn sum-with [self others]
  (dr/with-primitive-buffer [others-buf :uint8 others]
    (c-sum-with (:ptr self) others-buf (count others))
  )
)

(ffi/defcfn ^:private c-sum-with-i32 "jolt_Thingy_sum_with_i32" [:pointer :pointer :size_t] :int64)
(defn sum-with-i32 [self others]
  (dr/with-primitive-buffer [others-buf :int others]
    (c-sum-with-i32 (:ptr self) others-buf (count others))
  )
)

(ffi/defcfn ^:private c-describe2 "jolt_Thingy_describe2" [:pointer :int :double :pointer] :void)
(defn describe2 [self opts]
  (let [buf (ffi/alloc 256) w (ffi/alloc dr/writeable-struct-size)]
    (try
      (dr/simple-write! buf 256 w)
      (c-describe2 (:ptr self) (mode/kw->int (:mode opts)) (:scale opts) w)
      (let [n (ffi/read w :size_t dr/O-len)] (ffi/read-bytes buf n))
      (finally (ffi/free buf) (ffi/free w))))
)

(ffi/defcfn ^:private c-describe3 "jolt_Thingy_describe3" [:pointer :double :double :double :pointer] :void)
(defn describe3 [self opts]
  (let [buf (ffi/alloc 256) w (ffi/alloc dr/writeable-struct-size)]
    (try
      (dr/simple-write! buf 256 w)
      (c-describe3 (:ptr self) (:x (:point opts)) (:y (:point opts)) (:scale opts) w)
      (let [n (ffi/read w :size_t dr/O-len)] (ffi/read-bytes buf n))
      (finally (ffi/free buf) (ffi/free w))))
)

(ffi/defcfn ^:private c-double "Thingy_double" [:pointer] :pointer)
(defn double [self] (doubled/->Doubled (c-double (:ptr self)) false))

