//! `jolt` Diplomat backend — skeleton.
//!
//! Lives at `tool/src/jolt/mod.rs` in a Diplomat checkout (add `pub mod jolt;`
//! to `tool/src/lib.rs`), mirroring the structure of the existing `c`/`cpp`/`js`
//! backends. This is a starting skeleton, not verified against a specific
//! diplomat_core version's exact HIR API — confirm signatures against
//! `tool/src/c/mod.rs` in the checkout you're building against before relying
//! on this compiling as-is (Milestone 1 in PLAN.md: read the real generated
//! header first).
//!
//! Design decisions baked in here (see PLAN.md for rationale):
//!   - opaque types  -> Jolt defrecord wrapping a :ptr, lifetime per the
//!                      :diplomat/lifecycle config (guardian vs explicit close!)
//!   - Result<T, E>  -> ex-info on Err, unwrapped value on Ok
//!   - structs       -> a generated offset table + accessor fns, not hand
//!                      copied byte offsets
//!   - slices        -> ffi/write-array, documented as copied

use diplomat_core::hir::{
    self, EnumDef, Method, OpaqueDef, ReturnType, StructDef, SuccessType, TypeContext, TypeDef,
    TypeId,
};
use std::fmt::Write as _;

pub struct JoltContext<'a> {
    pub tcx: &'a TypeContext,
}

/// Entry point: one .clj file per Diplomat type definition, mirroring how
/// the C backend emits one header per type.
pub fn gen_all(tcx: &TypeContext) -> Vec<(String, String)> {
    let ctx = JoltContext { tcx };
    let mut out = Vec::new();
    for (type_id, def) in tcx.all_types() {
        let (filename, contents) = match def {
            TypeDef::Opaque(o) => (format!("{}.clj", o.name), gen_opaque(&ctx, type_id, o)),
            TypeDef::Struct(s) => (format!("{}.clj", s.name), gen_struct(&ctx, type_id, s)),
            TypeDef::Enum(e) => (format!("{}.clj", e.name), gen_enum(&ctx, type_id, e)),
            _ => continue, // out-structs, traits, etc. — fill in as needed
        };
        out.push((filename, contents));
    }
    out
}

// ---------------------------------------------------------------------------
// Opaque types -> defrecord wrapping a pointer, one defcfn per method.
// ---------------------------------------------------------------------------

fn gen_opaque(ctx: &JoltContext, type_id: TypeId, def: &OpaqueDef) -> String {
    let name = &def.name;
    let mut out = String::new();

    let _ = writeln!(out, "(ns diplomat.{}", to_kebab_ns(name));
    let _ = writeln!(out, "  \"Generated by diplomat-tool --jolt. Do not edit by hand.\"");
    let _ = writeln!(out, "  (:require [jolt.ffi :as ffi]");
    let _ = writeln!(out, "            [diplomat.runtime :as dr]))");
    let _ = writeln!(out);

    // Opaque record: just a pointer. Lifecycle handled by diplomat.runtime,
    // not inlined here — keeps the guardian-vs-explicit-close! decision a
    // one-line config change rather than a codegen branch everywhere.
    let _ = writeln!(out, "(dr/defopaque {} \"{}_destroy\")", name, name);
    let _ = writeln!(out);

    for method in &def.methods {
        emit_method(ctx, &mut out, name, method);
    }

    out
}

fn emit_method(_ctx: &JoltContext, out: &mut String, owner: &str, method: &Method) {
    let c_symbol = format!("{}_{}", owner, method.name);
    let fn_name = to_kebab(&method.name);

    // Real implementation: walk method.params for argtypes, method.output
    // for rettype, dispatch on ReturnType::Infallible vs ::Fallible(Result)
    // to decide whether the generated Jolt fn wraps the call in
    // dr/unwrap-result!, and on whether any param is a &mut DiplomatWrite
    // to decide whether it wraps in dr/writeable-capture instead of
    // returning directly. Sketch:

    match &method.output {
        ReturnType::Infallible(SuccessType::Writeable) => {
            let _ = writeln!(
                out,
                "(defn {} [this]\n  (dr/writeable-capture (partial ffi/foreign-fn \"{}\" [...] :void) this))\n",
                fn_name, c_symbol
            );
        }
        ReturnType::Fallible(_ok, _err) => {
            let _ = writeln!(
                out,
                "(defn {} [this & args]\n  (dr/unwrap-result! (apply c-{} (:ptr this) args)))\n",
                fn_name, c_symbol
            );
        }
        _ => {
            let _ = writeln!(
                out,
                "(ffi/defcfn {} \"{}\" [:pointer ...] ...)\n",
                fn_name, c_symbol
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Non-opaque structs -> generated offset table instead of hand-copied bytes.
// This is the piece that retires the native-interop guide's manual
// "structs by offset" section.
// ---------------------------------------------------------------------------

fn gen_struct(_ctx: &JoltContext, _type_id: TypeId, def: &StructDef) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "(ns diplomat.{}", to_kebab_ns(&def.name));
    let _ = writeln!(out, "  (:require [jolt.ffi :as ffi]))");
    let _ = writeln!(out);

    // Field order and Rust-side layout come from def.fields (name + type);
    // real impl computes offsets via a small companion Rust binary that
    // does std::mem::offset_of!/size_of on the #[repr(C)] shim Diplomat
    // generates, emitted here as data rather than committed by hand.
    let _ = writeln!(out, "(def ^:private field-offsets");
    let _ = writeln!(out, "  ;; {{:field-name [byte-offset ffi-type]}} — placeholder,");
    let _ = writeln!(out, "  ;; filled by the offset-table generator, not by hand.");
    let _ = writeln!(out, "  {{}})");
    let _ = writeln!(out);
    let _ = writeln!(out, "(def sizeof-{} 0) ;; from generated offset table", to_kebab(&def.name));
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "(defn ->ptr [{{:keys [{}] :as m}}]\n  (dr/struct->ptr field-offsets sizeof-{} m))",
        def.fields.iter().map(|f| to_kebab(&f.name)).collect::<Vec<_>>().join(" "),
        to_kebab(&def.name)
    );

    out
}

// ---------------------------------------------------------------------------
// C-like enums -> keyword <-> int table, generated instead of hand-copied
// (same shape as glimmer.genum, minus the runtime GObject-registry trick —
// Diplomat enums are plain ints, so this is a static table).
// ---------------------------------------------------------------------------

fn gen_enum(_ctx: &JoltContext, _type_id: TypeId, def: &EnumDef) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "(ns diplomat.{}", to_kebab_ns(&def.name));
    let _ = writeln!(out, "  \"Generated by diplomat-tool --jolt.\")");
    let _ = writeln!(out);
    let _ = writeln!(out, "(def kw->int");
    let _ = writeln!(out, "  {{");
    for (i, variant) in def.variants.iter().enumerate() {
        let _ = writeln!(out, "   :{} {}", to_kebab(&variant.name), i);
    }
    let _ = writeln!(out, "   }})");
    let _ = writeln!(out);
    let _ = writeln!(out, "(def int->kw (clojure.set/map-invert kw->int))");
    out
}

// ---------------------------------------------------------------------------
// Naming helpers — Rust CamelCase/snake_case -> Clojure kebab-case.
// ---------------------------------------------------------------------------

fn to_kebab(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.char_indices() {
        if c == '_' {
            out.push('-');
        } else if c.is_uppercase() && i != 0 {
            out.push('-');
            out.extend(c.to_lowercase());
        } else {
            out.extend(c.to_lowercase());
        }
    }
    out
}

fn to_kebab_ns(s: &str) -> String {
    to_kebab(s)
}
