// GENERATED by jolt-diplomat-backend. Do not hand-edit.
#include <string.h>
#include "diplomat_runtime.h"
#include "AllocStats.h"
#include "Reducer.h"

void jolt_diplomat_simple_write(char* buf, size_t buf_size, void* out) {
    DiplomatWrite w = diplomat_simple_write(buf, buf_size);
    memcpy(out, &w, sizeof(w));
}

int32_t jolt_Reducer_reduce(const int32_t* items_data, size_t items_len, const void* f_data, int32_t (*f_run_callback)(const void*, int32_t, int32_t), void (*f_destructor)(const void*)) {
    return Reducer_reduce((DiplomatI32View){ .data = items_data, .len = items_len }, (DiplomatCallback_Reducer_reduce_f){ .data = f_data, .run_callback = f_run_callback, .destructor = f_destructor });
}

int32_t jolt_Reducer_apply_twice(int32_t x, const void* f_data, int32_t (*f_run_callback)(const void*, int32_t), void (*f_destructor)(const void*)) {
    return Reducer_apply_twice(x, (DiplomatCallback_Reducer_apply_twice_f){ .data = f_data, .run_callback = f_run_callback, .destructor = f_destructor });
}

int32_t jolt_Reducer_apply_twice_leaky(int32_t x, const void* f_data, int32_t (*f_run_callback)(const void*, int32_t), void (*f_destructor)(const void*)) {
    return Reducer_apply_twice_leaky(x, (DiplomatCallback_Reducer_apply_twice_leaky_f){ .data = f_data, .run_callback = f_run_callback, .destructor = f_destructor });
}

