(ns diplomat.doubled
  "GENERATED by jolt-diplomat-backend from the real Diplomat HIR.
  Do not hand-edit — see findings/milestone-5-findings.md."
  (:require [jolt.ffi :as ffi]
            [diplomat.runtime :as dr]
  ))

(dr/defopaque Doubled "Doubled_destroy")

(ffi/defcfn ^:private c-value "Doubled_value" [:pointer] :uint)
(defn value [self] (c-value (:ptr self)))

