// GENERATED by jolt-diplomat-backend. Do not hand-edit.
#include <string.h>
#include "diplomat_runtime.h"
#include "Doubled.h"
#include "Thingy.h"

void jolt_diplomat_simple_write(char* buf, size_t buf_size, void* out) {
    DiplomatWrite w = diplomat_simple_write(buf, buf_size);
    memcpy(out, &w, sizeof(w));
}

// (DiplomatCallback constructed inline below)
uint8_t jolt_Thingy_apply_callback(const Thingy* self, const void* f_data, uint8_t (*f_run_callback)(const void*, uint8_t), void (*f_destructor)(const void*)) {
    return Thingy_apply_callback(self, (DiplomatCallback_Thingy_apply_callback_f){ .data = f_data, .run_callback = f_run_callback, .destructor = f_destructor });
}

void jolt_Thingy_try_create(const char* s_data, size_t s_len, void* out) {
    Thingy_try_create_result r = Thingy_try_create((DiplomatStringView){ .data = s_data, .len = s_len });
    memcpy(out, &r, sizeof(r));
}

size_t jolt_sizeof_Thingy_try_create_result(void) { return sizeof(Thingy_try_create_result); }
// (constructed inline below, possibly nested)
void jolt_Thingy_describe(const Thingy* self, bool opts_verbose, double opts_scale, DiplomatWrite* write) {
    return Thingy_describe(self, (ThingyOptions){ .verbose = opts_verbose, .scale = opts_scale }, write);
}

uint32_t jolt_Thingy_sum_with(const Thingy* self, const uint8_t* others_data, size_t others_len) {
    return Thingy_sum_with(self, (DiplomatU8View){ .data = others_data, .len = others_len });
}

int64_t jolt_Thingy_sum_with_i32(const Thingy* self, const int32_t* others_data, size_t others_len) {
    return Thingy_sum_with_i32(self, (DiplomatI32View){ .data = others_data, .len = others_len });
}

// (constructed inline below, possibly nested)
void jolt_Thingy_describe2(const Thingy* self, Mode opts_mode, double opts_scale, DiplomatWrite* write) {
    return Thingy_describe2(self, (ThingyOptions2){ .mode = opts_mode, .scale = opts_scale }, write);
}

// (constructed inline below, possibly nested)
void jolt_Thingy_describe3(const Thingy* self, double opts_point_x, double opts_point_y, double opts_scale, DiplomatWrite* write) {
    return Thingy_describe3(self, (ThingyOptions3){ .point = (Point){ .x = opts_point_x, .y = opts_point_y }, .scale = opts_scale }, write);
}

