(ns diplomat.bidi-paragraph
  "GENERATED by jolt-diplomat-backend from the real Diplomat HIR.
  Do not hand-edit — see findings/milestone-5-findings.md."
  (:require [jolt.ffi :as ffi]
            [diplomat.runtime :as dr]
  ))

(dr/defopaque BidiParagraph "BidiParagraph_destroy")

(ffi/defcfn ^:private c-set-paragraph-in-text "BidiParagraph_set_paragraph_in_text" [:pointer :size_t] :int)
(defn set-paragraph-in-text [self n] (c-set-paragraph-in-text (:ptr self) n))

(ffi/defcfn ^:private c-size "BidiParagraph_size" [:pointer] :size_t)
(defn size [self] (c-size (:ptr self)))

(ffi/defcfn ^:private c-range-start "BidiParagraph_range_start" [:pointer] :size_t)
(defn range-start [self] (c-range-start (:ptr self)))

(ffi/defcfn ^:private c-range-end "BidiParagraph_range_end" [:pointer] :size_t)
(defn range-end [self] (c-range-end (:ptr self)))

(ffi/defcfn ^:private c-level-at "BidiParagraph_level_at" [:pointer :size_t] :uint8)
(defn level-at [self pos] (c-level-at (:ptr self) pos))

