(ns diplomat.bidi
  "GENERATED by jolt-diplomat-backend from the real Diplomat HIR.
  Do not hand-edit — see findings/milestone-5-findings.md."
  (:require [jolt.ffi :as ffi]
            [diplomat.runtime :as dr]
  ))

(dr/defopaque Bidi "Bidi_destroy")

(ffi/defcfn ^:private c-create "Bidi_create" [] :pointer)
(defn create [] (->Bidi (c-create ) false))

(ffi/defcfn ^:private c-create-with-provider "jolt_Bidi_create_with_provider" [:pointer :pointer] :void)
(ffi/defcfn ^:private c-sizeof-create-with-provider-result "jolt_sizeof_Bidi_create_with_provider_result" [] :int)
(defn create-with-provider [provider]
  (let [sz (c-sizeof-create-with-provider-result) out (ffi/alloc sz)]
    (try
      (c-create-with-provider (:ptr provider) out)
      (dr/unwrap-result!
       (if (= 1 (ffi/read out :uint8 8))
         {:ok? true :value (->Bidi (ffi/read out :pointer 0) false)}
         {:ok? false :error (ffi/read out :int 0)})
       "Bidi/create-with-provider")
      (finally (ffi/free out))))
)

(ffi/defcfn ^:private c-level-is-rtl "Bidi_level_is_rtl" [:uint8] :int)
(defn level-is-rtl [level] (c-level-is-rtl level))

(ffi/defcfn ^:private c-level-is-ltr "Bidi_level_is_ltr" [:uint8] :int)
(defn level-is-ltr [level] (c-level-is-ltr level))

(ffi/defcfn ^:private c-level-rtl "Bidi_level_rtl" [] :uint8)
(defn level-rtl [] (c-level-rtl ))

(ffi/defcfn ^:private c-level-ltr "Bidi_level_ltr" [] :uint8)
(defn level-ltr [] (c-level-ltr ))

