(ns diplomat.bidi-info
  "GENERATED by jolt-diplomat-backend from the real Diplomat HIR.
  Do not hand-edit — see findings/milestone-5-findings.md."
  (:require [jolt.ffi :as ffi]
            [diplomat.runtime :as dr]
            [diplomat.bidi-paragraph :as bidi-paragraph]
  ))

(dr/defopaque BidiInfo "BidiInfo_destroy")

(ffi/defcfn ^:private c-paragraph-count "BidiInfo_paragraph_count" [:pointer] :size_t)
(defn paragraph-count [self] (c-paragraph-count (:ptr self)))

(ffi/defcfn ^:private c-paragraph-at "BidiInfo_paragraph_at" [:pointer :size_t] :pointer)
(defn paragraph-at [self n] (bidi-paragraph/->BidiParagraph (c-paragraph-at (:ptr self) n) false))

(ffi/defcfn ^:private c-size "BidiInfo_size" [:pointer] :size_t)
(defn size [self] (c-size (:ptr self)))

(ffi/defcfn ^:private c-level-at "BidiInfo_level_at" [:pointer :size_t] :uint8)
(defn level-at [self pos] (c-level-at (:ptr self) pos))

