(ns diplomat.calendar
  "GENERATED by jolt-diplomat-backend from the real Diplomat HIR.
  Do not hand-edit — see findings/milestone-5-findings.md."
  (:require [jolt.ffi :as ffi]
            [diplomat.runtime :as dr]
  ))

(dr/defopaque Calendar "Calendar_destroy")

