(ns diplomat.reordered-index-map
  "GENERATED by jolt-diplomat-backend from the real Diplomat HIR.
  Do not hand-edit — see findings/milestone-5-findings.md."
  (:require [jolt.ffi :as ffi]
            [diplomat.runtime :as dr]
  ))

(dr/defopaque ReorderedIndexMap "ReorderedIndexMap_destroy")

(ffi/defcfn ^:private c-len "ReorderedIndexMap_len" [:pointer] :size_t)
(defn len [self] (c-len (:ptr self)))

(ffi/defcfn ^:private c-is-empty "ReorderedIndexMap_is_empty" [:pointer] :int)
(defn is-empty [self] (c-is-empty (:ptr self)))

(ffi/defcfn ^:private c-get "ReorderedIndexMap_get" [:pointer :size_t] :size_t)
(defn get [self index] (c-get (:ptr self) index))

