(ns diplomat.json-kind
  "GENERATED by jolt-diplomat-backend.")

(def kw->int {
  :null 0
  :bool 1
  :number 2
  :string 3
  :array 4
  :object 5
  })

(def int->kw (clojure.set/map-invert kw->int))
