(ns diplomat.alloc-stats
  "GENERATED by jolt-diplomat-backend from the real Diplomat HIR.
  Do not hand-edit — see backend/src/main.rs for the generator, README.md for how this fits together."
  (:require [jolt.ffi :as ffi]
            [diplomat.runtime :as dr]
  ))

(dr/defopaque AllocStats "b64_AllocStats_destroy_mv1")

(ffi/defcfn ^:private c-bytes-allocated "b64_AllocStats_bytes_allocated_mv1" [] :uint64)
(defn bytes-allocated [] (c-bytes-allocated ))

(ffi/defcfn ^:private c-bytes-deallocated "b64_AllocStats_bytes_deallocated_mv1" [] :uint64)
(defn bytes-deallocated [] (c-bytes-deallocated ))

