//! Resolves finding #3 from milestone-1-findings.md for real: computes
//! field offsets by pointer arithmetic (addr_of!, stable since Rust 1.51 —
//! deliberately not using the offset_of! macro, which needs rustc 1.77+
//! and this environment only has 1.75) against the REAL struct definitions
//! copied from out-c-real/diplomat_runtime.h and ThingyOptions.d.h, rather
//! than hand-copied numbers.
//!
//! This is the actual tool Milestone 6 describes: run it against any
//! Diplomat-generated struct, get back an EDN offset table, never
//! hand-maintain offsets again.

use std::mem::{align_of, size_of};

// Mirror of the REAL generated struct, copied field-for-field from
// out-c-real/diplomat_runtime.h — not the pre-spike guess.
#[repr(C)]
struct DiplomatWrite {
    context: *mut std::ffi::c_void,
    buf: *mut i8,
    len: usize,
    cap: usize,
    grow_failed: bool,
    flush: *const std::ffi::c_void, // fn pointer, same size/align as *const ()
    grow: *const std::ffi::c_void,
}

// Mirror of the REAL generated ThingyOptions.d.h struct.
#[repr(C)]
struct ThingyOptions {
    verbose: bool,
    scale: f64,
}

macro_rules! field_offset {
    ($ty:ty, $field:ident) => {{
        let base: *const $ty = std::ptr::null();
        let field_ptr = unsafe { std::ptr::addr_of!((*base).$field) };
        field_ptr as usize
    }};
}

fn emit_edn(name: &str, size: usize, align: usize, fields: &[(&str, usize)]) {
    println!("(def ^:generated {}-layout", to_kebab(name));
    println!("  ;; DO NOT hand-edit — generated by offset-gen from the real");
    println!("  ;; Diplomat C header. Re-run offset-gen if the header changes.");
    println!("  {{:size {} :align {}", size, align);
    println!("   :fields");
    println!("   {{");
    for (fname, offset) in fields {
        println!("    :{} {}", to_kebab(fname), offset);
    }
    println!("    }}}})");
    println!();
}

fn to_kebab(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.char_indices() {
        if c == '_' {
            out.push('-');
        } else if c.is_uppercase() && i != 0 {
            out.push('-');
            out.extend(c.to_lowercase());
        } else {
            out.extend(c.to_lowercase());
        }
    }
    out
}

fn main() {
    println!("(ns diplomat.generated-offsets");
    println!("  \"Generated by offset-gen against real Diplomat C headers.");
    println!("  Resolves milestone-1-findings.md finding #3 — replaces the");
    println!("  hand-copied (and wrong) offsets that were in diplomat/runtime.clj.\")");
    println!();

    emit_edn(
        "DiplomatWrite",
        size_of::<DiplomatWrite>(),
        align_of::<DiplomatWrite>(),
        &[
            ("context", field_offset!(DiplomatWrite, context)),
            ("buf", field_offset!(DiplomatWrite, buf)),
            ("len", field_offset!(DiplomatWrite, len)),
            ("cap", field_offset!(DiplomatWrite, cap)),
            ("grow_failed", field_offset!(DiplomatWrite, grow_failed)),
            ("flush", field_offset!(DiplomatWrite, flush)),
            ("grow", field_offset!(DiplomatWrite, grow)),
        ],
    );

    emit_edn(
        "ThingyOptions",
        size_of::<ThingyOptions>(),
        align_of::<ThingyOptions>(),
        &[
            ("verbose", field_offset!(ThingyOptions, verbose)),
            ("scale", field_offset!(ThingyOptions, scale)),
        ],
    );
}
