// GENERATED by jolt-diplomat-backend. Do not hand-edit.
#include <string.h>
#include "diplomat_runtime.h"

void jolt_diplomat_simple_write(char* buf, size_t buf_size, void* out) {
    DiplomatWrite w = diplomat_simple_write(buf, buf_size);
    memcpy(out, &w, sizeof(w));
}

