[package]
name = "markdown_capi"
version = "0.1.0"
edition = "2021"

[lib]
name = "markdown_capi"
crate-type = ["cdylib"]

[features]
mem-trace = ["dep:stats_alloc"]

[dependencies]
diplomat = ">=0.10,<0.16"
diplomat-runtime = ">=0.10,<0.16"
pulldown-cmark = "0.13"
stats_alloc = { version = "0.1", optional = true }
