(ns diplomat.generated-offsets
  "Generated by offset-gen against real Diplomat C headers.
  Resolves milestone-1-findings.md finding #3 — replaces the
  hand-copied (and wrong) offsets that were in diplomat/runtime.clj.")

(def ^:generated diplomat-write-layout
  ;; DO NOT hand-edit — generated by offset-gen from the real
  ;; Diplomat C header. Re-run offset-gen if the header changes.
  {:size 56 :align 8
   :fields
   {
    :context 0
    :buf 8
    :len 16
    :cap 24
    :grow-failed 32
    :flush 40
    :grow 48
    }})

(def ^:generated thingy-options-layout
  ;; DO NOT hand-edit — generated by offset-gen from the real
  ;; Diplomat C header. Re-run offset-gen if the header changes.
  {:size 16 :align 8
   :fields
   {
    :verbose 0
    :scale 8
    }})

;; NOTE (severity #4, superseded): a thingy-try-create-result-layout entry
;; used to live here, hand-copying Thingy_try_create_result's is_ok
;; offset into a static table. Removed — every real generated crate
;; (examples/regex, examples/base64, ...) instead fetches per-struct
;; sizeof/offsetof from a generated C shim at load time
;; (jolt_sizeof_*_result / jolt_offsetof_*_result_is_ok), which is the
;; actual codegen contract this file's own docstring describes. thingy.clj
;; now follows that pattern instead of duplicating it here.

