(ns diplomat.generated-offsets
  "Generated by offset-gen against real Diplomat C headers.
  Resolves milestone-1-findings.md finding #3 — replaces the
  hand-copied (and wrong) offsets that were in diplomat/runtime.clj.")

(def ^:generated diplomat-write-layout
  ;; DO NOT hand-edit — generated by offset-gen from the real
  ;; Diplomat C header. Re-run offset-gen if the header changes.
  {:size 56 :align 8
   :fields
   {
    :context 0
    :buf 8
    :len 16
    :cap 24
    :grow-failed 32
    :flush 40
    :grow 48
    }})

(def ^:generated thingy-options-layout
  ;; DO NOT hand-edit — generated by offset-gen from the real
  ;; Diplomat C header. Re-run offset-gen if the header changes.
  {:size 16 :align 8
   :fields
   {
    :verbose 0
    :scale 8
    }})

