(ns diplomat.url-error
  "GENERATED by jolt-diplomat-backend from the real Diplomat HIR.
  Do not hand-edit — see backend/src/main.rs for the generator, README.md for how this fits together."
  (:require [jolt.ffi :as ffi]
            [diplomat.runtime :as dr]
  ))

(dr/defopaque UrlError "url_UrlError_destroy_mv1")

(ffi/defcfn ^:private c-message "jolt_url_UrlError_message_mv1" [:pointer :pointer] :void)
(defn message [self]
  (dr/writeable-capture (fn [w__] (c-message (dr/ptr! self) w__)))
)

