(ns diplomat.version-req
  "GENERATED by jolt-diplomat-backend from the real Diplomat HIR.
  Do not hand-edit — see backend/src/main.rs for the generator, README.md for how this fits together."
  (:require [jolt.ffi :as ffi]
            [diplomat.runtime :as dr]
            [diplomat.parse-error :as parse-error]
  ))

(dr/defopaque VersionReq "sv_VersionReq_destroy_mv1")

(ffi/defcfn ^:private c-parse "jolt_sv_VersionReq_parse_mv1" [:string :size_t :pointer] :void)
(ffi/defcfn ^:private c-sizeof-parse-result "jolt_sizeof_sv_VersionReq_parse_mv1_result" [] :int)
(ffi/defcfn ^:private c-is-ok-offset-parse "jolt_offsetof_sv_VersionReq_parse_mv1_result_is_ok" [] :int)
(def ^:private sz-parse-result (delay (c-sizeof-parse-result)))
(def ^:private is-ok-off-parse (delay (c-is-ok-offset-parse)))
(defn parse [text]
  (ffi/with-alloc [out @sz-parse-result]
    (c-parse text (count text) out)
    (dr/unwrap-result!
     (if (= 1 (ffi/read out :uint8 @is-ok-off-parse))
       {:ok? true :value (->VersionReq (ffi/read out :pointer 0) (atom false))}
       {:ok? false :error (parse-error/->ParseError (ffi/read out :pointer 0) (atom false))})
       "VersionReq/parse" parse-error/message)
  )
)

(ffi/defcfn ^:private c-matches "jolt_sv_VersionReq_matches_mv1" [:pointer :pointer] :int)
(defn matches [self version]
  (c-matches (dr/ptr! self) (dr/ptr! version))
)

(ffi/defcfn ^:private c-to-string "jolt_sv_VersionReq_to_string_mv1" [:pointer :pointer] :void)
(defn to-string [self]
  (dr/writeable-capture (fn [w__] (c-to-string (dr/ptr! self) w__)))
)

