(ns diplomat.audio-stream
  "GENERATED by jolt-diplomat-backend from the real Diplomat HIR.
  Do not hand-edit — see backend/src/main.rs for the generator, README.md for how this fits together."
  (:require [jolt.ffi :as ffi]
            [diplomat.runtime :as dr]
            [diplomat.audio-error :as audio-error]
  ))

(dr/defopaque AudioStream "sdl3_AudioStream_destroy_mv1")

(ffi/defcfn ^:private c-open "jolt_sdl3_AudioStream_open_mv1" [:int :pointer] :void :blocking)
(ffi/defcfn ^:private c-sizeof-open-result "jolt_sizeof_sdl3_AudioStream_open_mv1_result" [] :int)
(ffi/defcfn ^:private c-is-ok-offset-open "jolt_offsetof_sdl3_AudioStream_open_mv1_result_is_ok" [] :int)
(def ^:private sz-open-result (delay (c-sizeof-open-result)))
(def ^:private is-ok-off-open (delay (c-is-ok-offset-open)))
(defn open [sample-rate]
  (ffi/with-alloc [out @sz-open-result]
    (c-open sample-rate out)
    (dr/unwrap-result!
     (if (= 1 (ffi/read out :uint8 @is-ok-off-open))
       {:ok? true :value (->AudioStream (ffi/read out :pointer 0) (atom false))}
       {:ok? false :error (audio-error/->AudioError (ffi/read out :pointer 0) (atom false))})
       "AudioStream/open" audio-error/message)
  )
)

(ffi/defcfn ^:private c-queued-bytes "sdl3_AudioStream_queued_bytes_mv1" [:pointer] :int)
(defn queued-bytes [self] (c-queued-bytes (dr/ptr! self)))

(ffi/defcfn ^:private c-put-samples "jolt_sdl3_AudioStream_put_samples_mv1" [:pointer :pointer :size_t] :void)
(defn put-samples [self samples]
  (dr/with-primitive-buffer [samples-buf :float samples]
    (c-put-samples (dr/ptr! self) samples-buf (count samples))
  )
)

